server:
  port: 8082
  servlet:
    context-path: /api/v1

  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024

Spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, env

springdoc:
  override-with-generic-response: false


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher